### ISSUE TITLE
Suggestion: Consider adding made in Vietnam badge?

### ISSUE THREAD

**Issue by huytd** [lampts/awesome-made-by-vietnamese#1]
Hey, I'm Huy, member of a Vietnamese developer community called [WeBuild](https://webuild.community/).

We have a recent project that creates a Github badge for projects made by Vietnamese people, you can find out more details here https://github.com/webuild-community/badge

I think it's a good fit to put some badge like this one on your repo:

![](https://raw.githubusercontent.com/webuild-community/badge/master/svg/made.svg)

What do you think? :D

**Comment by lampts** [comment]
Why not? I'll do it.
